# Generated by Django 5.1.6 on 2025-02-26 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_album', to='images.uploadedimage'),
        ),
    ]
