# Generated by Django 5.1.6 on 2025-03-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_album_tags_alter_album_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
